### ISSUE TITLE
Support colors

### ISSUE THREAD

**Issue by XfedeX** [nemjit001/mc-rcon-client#5]
Instead of getting colors, i get `┬º` characters.

**Comment by nemjit001** [comment]
Hi, on what platform / shell are you running the client?

**Comment by XfedeX** [comment]
@nemjit001 I am running Windows 10's CMD.

**Comment by nemjit001** [comment]
> @nemjit001 I am running Windows 10's CMD.

Ah, Windows 10 CMD does not support ansi color codes, I currently only have linux support for colors.

Are the characters following the regular terminal output? Because this is a known issue that I am in the middle of solving.

**Comment by XfedeX** [comment]
Everything is fine apart colors and they are regular characters.

**Comment by nemjit001** [comment]
> Everything is fine apart colors and they are regular characters.

I just released version 1.1.0 of the client, could you check if this release also resolves your issue?

Currently all colours have been removed because I am redoing the entire UI, but in a next release they will be added back in.
